import "./globals.css";

export const metadata = {
	title: "Trinity",
	description: "Generated by Lavie",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="he">
			<head>
				<link
					rel="apple-touch-icon"
					sizes="180x180"
					href="/favicon.ico"
				/>
				<link rel="shortcut icon" href="/favicon.ico" />
				<link rel="manifest" href="/site.webmanifest" />
			</head>
			<body className="bg-[#F5F6F8] dark:bg-[#151516]">
				{children}
			</body>
		</html>
	);
}
