name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build the Docker image
      id: build_docker
      run: |
          version=$(cat package.json | jq -r '.version')
          echo "version=$version" >> $GITHUB_ENV
          docker build . --file Dockerfile --tag tralala:$version
          docker save tralala:$version | gzip  > tralala.tar.gz
          echo "package=tralala.tar.gz" >> $GITHUB_OUTPUT

    - name: Upload binaries to release
      if: ${{ steps.build_docker.outputs.package != 0 }}
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: "tralala.tar.gz"
        asset_name: "tralala.tar.gz"
        tag: ${{ env.version }}
        overwrite: true